### ISSUE TITLE
Critical Error (after last update 2.0.11.14)

### ISSUE THREAD

**Issue by Gil3X** [TheUnnamedOrganisation/RocketBot#100]
Doesnt matter which config i am using (tested without config) and installation (extracted fresh latest build to separate folder) - got a critical error each time after bot starts.

![rocket_crit_error](https://user-images.githubusercontent.com/26007748/27942550-01f3f8d4-62d8-11e7-9fc1-5088ffe5168e.png)

<details>
  <summary>Spoiler - Show error log</summary>
************** Текст исключения **************
System.InvalidOperationException: The navigation property 'PokemonTimestamp' cannot be added to the entity type 'Account' because its CLR type 'ICollection<PokemonTimestamp>' does not match the expected CLR type 'PokemonTimestamp'.
   в Microsoft.EntityFrameworkCore.Metadata.Internal.Navigation.IsCompatible(PropertyInfo navigationProperty, Type sourceClrType, Type targetClrType, Nullable`1 shouldBeCollection, Boolean shouldThrow)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddNavigation(PropertyIdentity propertyIdentity, ForeignKey foreignKey, Boolean pointsToPrincipal)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.Navigation(Nullable`1 propertyIdentity, ConfigurationSource configurationSource, Boolean runConventions, Boolean pointsToPrincipal)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.HasPrincipalToDependent(PropertyInfo property, ConfigurationSource configurationSource, Boolean runConventions)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, EntityType principalEntityType, EntityType dependentEntityType, Nullable`1 configurationSource, Boolean runConventions)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, Nullable`1 configurationSource, Boolean runConventions)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(InternalEntityTypeBuilder principalEntityTypeBuilder, InternalEntityTypeBuilder dependentEntityTypeBuilder, Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 isUnique, Nullable`1 isRequired, Nullable`1 deleteBehavior, Boolean removeCurrent, Boolean oldRelationshipInverted, Nullable`1 principalEndConfigurationSource, Nullable`1 configurationSource, Boolean runConventions, List`1 removedNavigations, List`1 removedForeignKeys)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(Nullable`1 configurationSource, InternalEntityTypeBuilder principalEntityTypeBuilder, InternalEntityTypeBuilder dependentEntityTypeBuilder, Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 isUnique, Nullable`1 isRequired, Nullable`1 deleteBehavior, Boolean removeCurrent, Nullable`1 principalEndConfigurationSource, Boolean oldRelationshipInverted, Boolean runConventions)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, EntityType principalEntityType, EntityType dependentEntityType, Nullable`1 configurationSource, Boolean runConventions)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, EntityType principalEntityType, EntityType dependentEntityType, Nullable`1 configurationSource)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, Nullable`1 configurationSource)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(PropertyInfo navigationToPrincipalProperty, PropertyInfo navigationToDependentProperty, ConfigurationSource configurationSource)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Relationship(InternalEntityTypeBuilder targetEntityTypeBuilder, Nullable`1 navigationToTarget, Nullable`1 inverseNavigation, ConfigurationSource configurationSource)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Relationship(InternalEntityTypeBuilder targetEntityTypeBuilder, PropertyInfo navigationToTarget, PropertyInfo inverseNavigation, ConfigurationSource configurationSource)
   в Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.CreateRelationships(IReadOnlyList`1 relationshipCandidates, InternalEntityTypeBuilder entityTypeBuilder)
   в Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.DiscoverRelationships(InternalEntityTypeBuilder entityTypeBuilder)
   в Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   в Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   в Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   в Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(EntityType entityType, Boolean runConventions)
   в Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource, Boolean runConventions)
   в Microsoft.EntityFrameworkCore.ModelBuilder.Entity(Type type)
   в Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.FindSets(ModelBuilder modelBuilder, DbContext context)
   в Microsoft.EntityFrameworkCore.Infrastructure.Internal.RelationalModelSource.FindSets(ModelBuilder modelBuilder, DbContext context)
   в Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   в System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   в Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   в Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   в Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   в Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   в Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   в Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   в Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   в Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   в Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   в Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_13(IServiceProvider p)
   в Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   в Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   в Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   в Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   в Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
   в Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   в PoGo.NecroBot.Logic.Utils.Statistics..ctor()
   в PoGo.NecroBot.Logic.State.Session..ctor(GlobalSettings globalSettings, ISettings settings, ILogicSettings logicSettings, IElevationService elevationService, ITranslation translation)
   в RocketBot2.Forms.MainForm.InitializeBot(Action`2 onBotStarted)
   в RocketBot2.Forms.MainForm.MainForm_Load(Object sender, EventArgs e)
   в System.Windows.Forms.Form.OnLoad(EventArgs e)
   в System.Windows.Forms.Form.OnCreateControl()
   в System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   в System.Windows.Forms.Control.CreateControl()
   в System.Windows.Forms.Control.WmShowWindow(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.Form.WmShowWindow(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
RocketBot2
    Версия сборки: 2.11.0.14
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
GMap.NET.Core
    Версия сборки: 1.7.5.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
GMap.NET.WindowsForms
    Версия сборки: 1.7.5.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
ObjectListView
    Версия сборки: 2.9.1.1072
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data.SQLite
    Версия сборки: 1.0.98.0
    Версия Win32: 1.0.98.0
    CodeBase: file:///C:/Users/Gilt/AppData/Local/GMap.NET/DllCache/SQLite_v98_NET4_x64/System.Data.SQLite.DLL
----------------------------------------
System.Data
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
PoGo.NecroBot.Logic
    Версия сборки: 2.11.0.14
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
POGOProtos
    Версия сборки: 2.11.0.14
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
Google.Protobuf
    Версия сборки: 3.3.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
Pokemon.Go.Rocket.API
    Версия сборки: 2.11.0.14
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
CommandLine
    Версия сборки: 1.9.71.2
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
System.Net.Http
    Версия сборки: 4.1.1.1
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
Newtonsoft.Json
    Версия сборки: 10.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
System.Numerics
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Newtonsoft.Json.Schema
    Версия сборки: 3.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
System.Runtime.Serialization
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.ComponentModel.DataAnnotations.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations.resources/v4.0_4.0.0.0_ru_31bf3856ad364e35/System.ComponentModel.DataAnnotations.resources.dll
----------------------------------------
Microsoft.EntityFrameworkCore
    Версия сборки: 1.1.2.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Версия сборки: 1.1.1.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
System.Runtime
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.ComponentModel
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ComponentModel.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Версия сборки: 1.1.1.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
System.Collections
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Версия сборки: 1.1.2.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
Microsoft.Extensions.Logging
    Версия сборки: 1.1.2.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
System.Linq
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll
----------------------------------------
Microsoft.Extensions.Caching.Memory
    Версия сборки: 1.1.2.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
Remotion.Linq
    Версия сборки: 2.1.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
System.Interactive.Async
    Версия сборки: 3.0.3000.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
Microsoft.Extensions.Options
    Версия сборки: 1.1.2.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
Microsoft.Extensions.Caching.Abstractions
    Версия сборки: 1.1.2.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
System.Collections.Concurrent
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections.Concurrent/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.Concurrent.dll
----------------------------------------
System.Reflection
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll
----------------------------------------
System.Threading
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll
----------------------------------------
System.Runtime.Extensions
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll
----------------------------------------
System.Threading.Tasks
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Версия сборки: 0.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.EntityFrameworkCore.Sqlite
    Версия сборки: 1.1.2.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
Microsoft.EntityFrameworkCore.Relational
    Версия сборки: 1.1.2.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
System.Diagnostics.DiagnosticSource
    Версия сборки: 4.0.2.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
System.Linq.Expressions
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Linq.Expressions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.Expressions.dll
----------------------------------------
System.Collections.Immutable
    Версия сборки: 1.2.1.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
Microsoft.Data.Sqlite
    Версия сборки: 1.1.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///E:/_Shared/RocketBot/2.1.0.14/RocketBot2.exe
----------------------------------------
System.EnterpriseServices
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Runtime.Caching
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
----------------------------------------
System.Globalization
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Globalization/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Globalization.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.36213 built by: FX452RTMLDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
</details>

**Comment by Furtif** [comment]
hello ,
try to delete caches folder, and accounts.db, auth.* config.* 
restart fallow assistant

**Comment by Gil3X** [comment]
See above --> extracted fresh latest build to separate folder, no caches, new auth and config created automatically

**Comment by Furtif** [comment]
yes... odd All this, the bot works well is the 1st error I see of this type, you installed net 4.6.2?

**Comment by Furtif** [comment]
See in discord https://discord.gg/y6EU2qY it may be that someone had this bug and has the solution

**Comment by Gil3X** [comment]
all prerequisites not changed - bot was running well until last update
also necro is running fine, so error somehow connected with rocket(gui?) latest update

**Comment by Furtif** [comment]
In this last version only the support 0.67.1 to 0.67.2 was changed, and also changed the function getgymdetails for gymgetinfo, both in the necro and in the rocket, if the rocket does not work for you in 2.11.0.14 the necro also does not fonciona in 1.0 .0.183 in logic, strange thing, but the other users do not have this bug neither I, everything works necro and the rocket

**Comment by Gil3X** [comment]
Yeah necro running ok, so thats why i supposed that reason is in gui (as rocket using same logic and config). And its only happened after update (2.11.0.14)

**Comment by Gil3X** [comment]
So its very strange behaviour, few of my different folders got this error - others was unaffected.
What i`ve done - reinstalled dot.net(4.7 - latest https://www.microsoft.com/en-us/download/details.aspx?id=55170&desc=dotnet47) downloaded previous (2.0.11.13) version - put my config/auth there, run it and let it update itself. This time all went smooth and i fixed all my issues

**Comment by Furtif** [comment]
Cool :-), you could close the issue?
