### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Nackenschelle** [TheUnnamedOrganisation/RocketBot#12]
************** Ausnahmetext **************
PokemonGo.RocketAPI.Exceptions.AuthConfigException: You have selected Pogodev API but not provide proper API Key
   bei PokemonGo.RocketAPI.Client..ctor(ISettings settings)
   bei PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings logicSettings)
   bei PoGo.NecroBot.Logic.State.Session..ctor(GlobalSettings globalSettings, ISettings settings, ILogicSettings logicSettings, IElevationService elevationService, ITranslation translation)
   bei RocketBot2.Forms.MainForm.InitializeBot(Action`2 onBotStarted) in RocketBot2\Forms\MainForm.cs:Zeile 1506.
   bei RocketBot2.Forms.MainForm.MainForm_Load(Object sender, EventArgs e) in MainForm.cs:Zeile 128.
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Furtif** [comment]
close and start bot

**Comment by Furtif** [comment]
if same bug use samples configs 
edit auth.json and set you account(s)  
if issue solved please close this issue thanks.
[confs.zip](https://github.com/TheUnnamedOrganisation/RocketBot/files/1202290/confs.zip)

**Comment by Nackenschelle** [comment]
just works if i use the old Config
is the login window no longer available?

**Comment by Furtif** [comment]
Once the config created and good the login window does not appear anymore if you want to add other accounts edit the auth.json file, in these examples that I gave the auth this in multiaccount mode, can serve as a base in simple mode account only puts a bot in the Array

**Comment by Furtif** [comment]
To as well check the mode of authtype google or PTC depending on the account that is used
