### ISSUE TITLE
cant compile latest build

### ISSUE THREAD

**Issue by Nackenschelle** [TheUnnamedOrganisation/RocketBot#24]
here is the error. http://prntscr.com/gjxjw1
how can i fix it?

**Comment by Furtif** [comment]
you feroxrev module and pogoprotos is outted recheck code https://github.com/TheUnnamedOrganisation/RocketBot#cloning-source-code

**Comment by Nackenschelle** [comment]
thanks

**Comment by Nackenschelle** [comment]
got the same issue :(

used git bash to clone the project but error still exist.

**Comment by Furtif** [comment]
if not compile appveyor would give error !! https://ci.appveyor.com/project/RocketBot/rocketbot/branch/master It's not the case! see it well it

**Comment by Nackenschelle** [comment]
ok i fixed the issue. reinstall visual studio fixed my problem
thanks <3

**Comment by Furtif** [comment]
If bug fixed please close this issue. Thanks
