### ISSUE TITLE
new buyed key is wrong?

### ISSUE THREAD

**Issue by Nackenschelle** [TheUnnamedOrganisation/RocketBot#46]
Hey i got a new error message with the latest build
http://prntscr.com/gq7wjx

Bot says my key is wrong but i just buyed it
is there any solution for me?

**Comment by Furtif** [comment]
hello, yes bug is present fixed at https://github.com/TheUnnamedOrganisation/RocketBot/pull/45 for uses bot use this sample auth.json 

[auth.zip](https://github.com/TheUnnamedOrganisation/RocketBot/files/1336617/auth.zip)

download it dezip copy edit auth.json file copy file and paste it to Config folder.
