### ISSUE TITLE
cant compile latest build

### ISSUE THREAD

**Issue by Nackenkelle** [TheUnnamedOrganisation/RocketBot#63]
i download the latest sc for testing but i cannot run the bot after setup login and position.
the bot restarts and than it wont open anymore.

i got following error
http://prntscr.com/ecvfq0

**Comment by Furtif** [comment]
Hum... Maybe your use multi account ... Make in to auth.conf this to false and delete accounts.db and try

**Comment by Furtif** [comment]
try now after rebase
