### ISSUE TITLE
Exception: Error refreshing access token.

### ISSUE THREAD

**Issue by Fail2Reap** [TheUnnamedOrganisation/RocketBot#64]
**Summary:**
When users log into RocketBot2 v2.7.0.10 or v2.7.0.9 they are now receiving PokemonGo.RocketAPI.Exceptions.TokenRefreshException: Error refreshing access token.

**Steps to reproduce:**
1. Download the latest version of RocketBot2.
2. Log in using a Google account.
3. The exception will usually occur after 15-30 seconds.

**Steps taken to try and resolve the issue:**
- Tried with different Google accounts.
- Tried generating a new API key.
- Tried a previous version of RocketBot2.

**Screenshot:**
![screenshot_2](https://cloud.githubusercontent.com/assets/7574753/23341906/5631244a-fc48-11e6-874d-aed76daad6d4.png)

**Comment by Furtif** [comment]
Delete all auth.* and all conf.* and start bot

**Comment by remynl** [comment]
Tried to delete auth and conf files didnt help

**Comment by Furtif** [comment]
Ops delete accounts.db

**Comment by Furtif** [comment]
All auth.* all conf.* and accounts.db sorry

**Comment by remynl** [comment]
Removed /temp & accounts.db , Configs, Result setup / and result in the same issue for me

**Comment by Furtif** [comment]
Configs?! Dir translation do not be removed!!

**Comment by remynl** [comment]
Tried multiple times no success at all

**Comment by Furtif** [comment]
Ok, by the time I'm in the hospital, I had a small problem with my left foot, I hope to come back soon to see its close because here I have my iphone. Without wifi in addition: - /
