### ISSUE TITLE
Issue with login

### ISSUE THREAD

**Issue by vaggos2** [TheUnnamedOrganisation/RocketBot#66]
After putting my account info on the gui program and I press start it pops a red message that says I need to fill my account info to the auth.json file and immediately shuts down.

After filling the username and password variables with the googleusername and googlepassword values it doesnt even open the gui, just starts on task manager and shuts down completely. I am using a google account which I have selected on the gui and it appears on the auth.json

**Comment by Furtif** [comment]
Hello, edit your auth.json 

"AuthConfig": {
    "AuthType": "google",
    "Username": "mon_mail@gmail.com",
    "Password": "mon_pass" 

or

"AuthConfig": {
    "AuthType": "ptc",
    "Username": "user",
    "Password": "pass"
