### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by mfbeni** [TheUnnamedOrganisation/RocketBot#67]
Hi, 

After the update v2.7.0.22 I'm getting the following message:

//============================================//
               POKEMON GO 0.57.4
//============================================//
RocketBot2 is compatible with 0.57.3 API.

We are investigating changes to the authentication that
Niantic made in 0.57.4. So the bot will be temporarily disabled.

 Unfortunately during this update Niantic has also attempted to 
block the Legacy 0.45 Service again.
//============================================//
               Updated: 3/07/2017

For support/questions:
OFFICIAL ROCKETBOT2 Discord: https://discord.gg/y6EU2qY

**Comment by Furtif** [comment]
0.57.4. update only pogodev api keys works go to discord and read annoncements

**Comment by mfbeni** [comment]
Thank you for answer. 
What I have to do?

**Comment by Furtif** [comment]
https://discord.gg/y6EU2qY channel #annoncements
