### ISSUE TITLE
one or more errors

### ISSUE THREAD

**Issue by shrevedealer** [TheUnnamedOrganisation/RocketBot#7]
every time i open it says one or more errors have occurred
![untitled](https://user-images.githubusercontent.com/30478288/28696101-36d88cdc-72f9-11e7-9f62-6da10e75f28a.png)

**Comment by Furtif** [comment]
Can you click details in the dialog and detail the error? Read the readme file and verify that you have installed the project dependencies.

**Comment by Furtif** [comment]
@shrevedealer no more bugs ? If allright close issue please.

**Comment by Furtif** [comment]
ok

**Comment by Nackenschelle** [comment]
same error here

**Comment by Furtif** [comment]
try samples config at https://github.com/TheUnnamedOrganisation/RocketBot/issues/12 maybe issue is solved
