### ISSUE TITLE
Release v2.9.1.6

### ISSUE THREAD

**Issue by Bardockish** [TheUnnamedOrganisation/RocketBot#75]
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at PokemonGo.RocketAPI.Rpc.Player.GetPlayer(Boolean addCommonRequests, Boolean addChallengeRequests)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\rocketbot2\FeroxRev\Rpc\Login.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.RocketBot.Logic.State.LoginState.<Execute>d__3.MoveNext() in c:\projects\rocketbot2\PoGo.RocketBot.Logic\State\LoginState.cs:line 55

**Comment by Furtif** [comment]
## Delete all preview config
+ accounts.db
+ config.json and auth.json
+ delete user folders (do not delete translations)

Start bot and reconfigure this by assistant

**Comment by Furtif** [comment]
ops not ok button sorry

**Comment by Bardockish** [comment]
I tried this already. Is it possible that my acc was banned?

**Comment by Furtif** [comment]
possible!

**Comment by Furtif** [comment]
try login in phone for see if ban

**Comment by Bardockish** [comment]
I tried now and I'm not banned. :(

**Comment by Furtif** [comment]
Cool if not banned is good news 👍 

# To run this requirements 

 - Microsoft  [.NET 4.6.2 SDK](https://www.microsoft.com/en-us/download/details.aspx?id=53321)
 - Windows 
- If you have trouble with bot configuration download the examples here [sample configs](https://github.com/Furtif/confs) edits auth.json by putting your account data

**Comment by Bardockish** [comment]
I'll try this requirement, but first i tried from another computer, and i still got the same error (attached).
![pic](https://cloud.githubusercontent.com/assets/26326697/25228511/13374d2a-25a3-11e7-9ab4-5a0958519f27.JPG)

**Comment by Furtif** [comment]
Estranho!!!! acho que és o unico com esse bug!

**Comment by Furtif** [comment]
This bug is due to the fact that the choice of mode is errored either to say `"Google"` or `"Ptc"` verified well the account data and the good syntax in auth.json to know:

      ``` "AuthType": "google" or "AuthType": "ptc" (lower)```

## See the error code and analysis of the lines involved.

Loginstate line [55](https://github.com/TheUnnamedOrganisation/PoGo.NecroBot.Logic/blob/master/State/LoginState.cs)

And

Login line [163](https://github.com/TheUnnamedOrganisation/FeroxRev/blob/master/Rpc/Login.cs)

**Comment by Furtif** [comment]
## MultiAccount Mode:
```
"Bots": [
    {
      "AuthType": "google",
      "Username": "myaccount@gmail.com",
      "Password": "123456"
    },
    {
      "AuthType": "ptc",
      "Username": "myaccountptc",
      "Password": "123456#"
    },
    {
      "AuthType": "ptc",
      "Username": "myaccount2",
      "Password": "123456#"
    }
  ],
```
## Single google account mode:
```
"Bots": [
    {
      "AuthType": "google",
      "Username": "myaccount@gmail.com",
      "Password": "123456"
    }
],
```
## Single ptc account mode:
```
"Bots": [
    {
      "AuthType": "ptc",
      "Username": "myaccount",
      "Password": "123456"
    }
],
```

**Comment by Bardockish** [comment]
Look at my auth.json attached.
![pic](https://cloud.githubusercontent.com/assets/26326697/25234087/6a0393ca-25b7-11e7-9214-b0057a40c04c.jpg)

**Comment by Furtif** [comment]
hum hum !! is ok try to generate a new DeviceConfig

**Comment by Bardockish** [comment]
Generated new deviceconfig, but still don't work...

I am only downloading "RocketBot2.zip". Do i need to download other files?

**Comment by Furtif** [comment]
Not rocketbot works alone, others are optional and work together with rocketbot, pokeease is a gui interface of rocketbot and the apk are the same as pokeease for android.

**Comment by Furtif** [comment]
What windows do you use windows 10 ???

**Comment by Bardockish** [comment]
Windows 7

**Comment by Furtif** [comment]
ha.... ok .... I have not tested in windows 7 I have that win 10, try this release compiled in "any cpu" mode instead of x86
[Release.zip](https://github.com/TheUnnamedOrganisation/RocketBot/files/943597/Release.zip)

**Comment by Furtif** [comment]
Will see if I can create a build win 7 in vs2017 .... have you try to compile the source code in win7 ???

**Comment by Bardockish** [comment]
Furtif, i just tried the requirement you sent earlier (Microsoft .NET 4.6.2 SDK), and now it's working. 

Thank you very much.
