### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by onelovebanan** [TheUnnamedOrganisation/RocketBot#99]
help pls 
[18:47:44] (INFO) System.Exception: Unexpected inventory error. Could not generate hash code.
   в PokemonGo.RocketAPI.Rpc.Inventory.GetInventoryItemHashKey(InventoryItem item)
   в PokemonGo.RocketAPI.Rpc.Inventory.AddRemoveOrUpdateItem(InventoryItem item)
   в PokemonGo.RocketAPI.Rpc.Inventory.MergeWith(GetInventoryResponse update)
   в PokemonGo.RocketAPI.Helpers.CommonRequest.ProcessGetInventoryResponse(Client client, GetInventoryResponse getInventoryResponse)
   в PokemonGo.RocketAPI.Rpc.Download.<GetRemoteConfigVersion>d6.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d10.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PoGo.RocketBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

**Comment by Furtif** [comment]
https://github.com/TheUnnamedOrganisation/RocketBot/releases/tag/v2.11.0.3

**Comment by Furtif** [comment]
fixed in x.4
